// gateway consts
export const USER_SERVICE_GATEWAY_BASE = '/user-manager/api/v1/';
export const FILE_MANAGE_GATEWAY_BASE = '/file-manager/api/v1/';
export const COMPOSE_GATEWAY_BASE = '/fe-compose/api/v1/';
export const IMAGE_GATEWAY_BASE = '/image-manager/api/v1/';
export const PROJECT_MANAGE_GATEWAY_BASE = '/project-manager/api/v1/';
export const TASK_MANAGE_GATEWAY_BASE = '/task-manager/api/v1/';
export const RESOURCE_MANAGE_GATEWAY_BASE = '/resource-manager/api/v1/';
export const SKYFLOW_MANAGE_GATEWAY_BASE = '/skyflow-manager/api/v1/';
export const SKYFLOW_MANAGE_GATEWAY_BASE_OLD = '/skyflow-manager/v2/';
export const SYSTEM_MANAGE_GETWAY_BASE = '/system-manager/api/v1/';
export const MODEL_MANAGE_GATEWAY_BASE = '/model-manager/api/v1/';
export const DATA_MANAGE_GATEWAY_BASE = '/data-manager/api/v1/';

export const IDE_MANAGER_GATEWAY_BASE = '/ide-manager/api/v1/';


// read auth consts
const SERVER_USER = 'USER-MANAGER';
const SERVER_PROJECT = 'PROJECT-MANAGER';
const SERVER_MODEL = 'MODEL-MANAGER';
const SERVER_IMAGE = 'IMAGE-MANAGER';
const SERVER_FILE = 'FILE-MANAGER';
const SERVER_DATA = 'DATA-MANAGER';
const SERVER_SKYFLOW = 'SKYFLOW-MANAGER';
const SERVER_RESOURCE = 'RESOURCE-MANAGER';
const SERVER_SYSTEM = 'SYSTEM-MANAGER';
const SERVER_TASK = 'TASK-MANAGER';

export default {

    // 资源管理读权限
    RESOURCE_TEMPLATE_READ: `${SERVER_RESOURCE}:TEMPLATE:READ:""`,
    RESOURCE_CONFIG_READ: `${SERVER_RESOURCE}:CONFIG:READ:""`,
    RESOURCE_USER_STATE_READ: `${SERVER_RESOURCE}:USER_STATE:READ:""`,
    RESOURCE_GLOBAL_STATE_READ: `${SERVER_RESOURCE}:GLOBAL_STATE:READ:""`,

    // 用户管理读权限
    USER_USER_READ: `${SERVER_USER}:USER:READ:""`,
    USER_GROUP_READ: `${SERVER_USER}:GROUP:READ:""`,
    USER_ROLE_READ: `${SERVER_USER}:ROLE:READ:""`,
    USER_PERMISSION_READ: `${SERVER_USER}:PERMISSION:READ:""`,
    USER_RESET_PASSWORD: `${SERVER_USER}:USER:PASSWORD-RESET:""`,

    // 监控中心读权限
    SYSTEM_GLOBAL_RESOURCE_READ: `${SERVER_SYSTEM}:GLOBAL_RESOURCE:READ:""`,
    SYSTEM_POD_REAL_RESOURCE_READ: `${SERVER_SYSTEM}:POD_REAL_RESOURCE:READ:""`,
    SYSTEM_POD_LOG_READ: `${SERVER_SYSTEM}:POD_LOG:READ:""`,
    SYSTEM_POD_STATE_READ: `${SERVER_SYSTEM}:POD_STATE:READ:""`,

    // 数据管理读权限
    DATA_DATA_SERVICE_READ: `${SERVER_DATA}:DATA_SERVICE:READ:""`,
    DATA_DATA_SOURCE_READ: `${SERVER_DATA}:DATA_SOURCE:READ:""`,
    DATA_DATA_SET_READ: `${SERVER_DATA}:DATA_SET:READ:""`,

    // 项目读权限
    PROJECT_PROJECT_READ: `${SERVER_PROJECT}:PROJECT:READ:""`,
    PROJECT_TEMPLATE_PROJECT_READ: `${SERVER_PROJECT}:TEMPLATE_PROJECT:READ:""`,
    PROJECT_COOPERATE_PROJECT_READ: `${SERVER_PROJECT}:COOPERATE_PROJECT:READ:""`,
    PROJECT_TASK_READ: `${SERVER_PROJECT}:TASK:READ:""`,

    // 镜像读权限
    IMAGE_IMAGE_READ: `${SERVER_IMAGE}:IMAGE:READ:""`,
    IMAGE_IMAGE_WRITE: `${SERVER_IMAGE}:IMAGE:WRITE:""`,
    IMAGE_IMAGE_SHARE: `${SERVER_IMAGE}:IMAGE:SHARE:""`,
    IMAGE_IMAGE_PACKAGE_READ: `${SERVER_IMAGE}:IMAGE_PACKAGE:READ:""`,
    IMAGE_IMAGE_BUILDER_READ: `${SERVER_IMAGE}:IMAGE_BUILDER:READ:""`,
    IMAGE_IMAGE_BUILDER_WRITE: `${SERVER_IMAGE}:IMAGE_BUILDER:WRITE:""`,
    IMAGE_IMAGE_BUILDER_BUILD_BASIC: `${SERVER_IMAGE}:IMAGE_BUILDER:BUILD_BASIC:""`,
    IMAGE_IMAGE_BUILDER_BUILD_TAR: `${SERVER_IMAGE}:IMAGE_BUILDER:BUILD_TAR:""`,
    IMAGE_IMAGE_BUILDER_BUILD_IMAGE_FILE: `${SERVER_IMAGE}:IMAGE_BUILDER:BUILD_IMAGE_FILE:""`,
    IMAGE_IMAGE_BUILDER_BUILD_CONTAINER_IMAGE: `${SERVER_IMAGE}:IMAGE_BUILDER:BUILD_CONTAINER_IMAGE:""`,
    IMAGE_IMAGE_SOURCE_REPOS_READ: `${SERVER_IMAGE}:IMAGE_SOURCE_REPOS:READ:""`,

    // 模型读权限
    MODEL_MODEL_READ: `${SERVER_MODEL}:MODEL:READ:""`,
    MODEL_MODEL_VERSION_READ: `${SERVER_MODEL}:MODEL_VERSION:READ:""`,

    // 文件读权限
    FILE_FILE_READ: `${SERVER_FILE}:FILE:READ:""`,

    // skyflow读权限
    SKYFLOW_FLOW_READ: `${SERVER_SKYFLOW}:FLOW:READ:""`,
    SKYFLOW_TEMPLATE_FLOW_READ: `${SERVER_SKYFLOW}:TEMPLATE_FLOW:READ:""`,
    SKYFLOW_FLOW_RECORD_READ: `${SERVER_SKYFLOW}:FLOW_RECORD:READ:""`,
    SKYFLOW_BASE_FIXED_COMPONENT_READ: `${SERVER_SKYFLOW}:BASE_FIXED_COMPONENT:READ:""`,
    SKYFLOW_NLP_FIXED_COMPONENT_READ: `${SERVER_SKYFLOW}:NLP_FIXED_COMPONENT:READ:""`,
    SKYFLOW_IMAGE_FIXED_COMPONENT_READ: `${SERVER_SKYFLOW}:FLOW:IMAGE_FIXED_COMPONENT:""`,
    SKYFLOW_FLOW_CUSTOMIZED_COMPONENT_READ: `${SERVER_SKYFLOW}:FLOW_CUSTOMIZED_COMPONENT:READ:""`,

    // 任务读权限
    TASK_TASK_READ:  `${SERVER_TASK}:TASK:READ:""`,
    TASK_EXECUTION_READ: `${SERVER_TASK}:EXECUTION:READ`,
};
