// 这里会枚举所有组件作为构建的入口

module.exports = {
    breadcrumb: './components/breadcrumb/index.js',
    'userinfo-dialog': './components/userinfo-dialog/index.js',
    'change-password': './components/change-password/index.js',
    'fold-label': './components/fold-label/index.js',
    'expand-label': './components/expand-label/index.js',
    projectcard: './components/projectcard/index.js',
    'select-group-user': './components/select-group-user/index.js',
    'file-select': './components/file-select/index.js',
    'search-layout': './components/search-layout/index.js',
    'user-picker': './components/user-picker/index.js',
    'share-setting': './components/share-setting/index.js',
    'pod-log': './components/pod-log/index.js',
    'task-list': './components/task-list/index.js',
    'task-start-dialog': './components/task-start-dialog/index.js',
    'task-stop-dialog': './components/task-stop-dialog/index.js',
    'code-editor': './components/code-editor/index.js',
    'resource-config': './components/resource-config/index.js',
    'auth': './components/auth/index.js',
    'share-form': './components/share-form/index.js',
    'task-running-limit': './components/task-running-limit/index.js',
    'lang-handle': './components/lang-handle/index.js',
    'subject-card': './components/subject-card/index.js',
    'create-project-card': './components/create-project-card/index.js',
};
