export SdxvJupyterDetail from './JupyterDetail';
export SdxvPythonDetail from './PythonDetail';
export SdxvSparkDetail from './SparkDetail';
export SdxvTensorflowDetail from './TensorflowDetail';
export SdxvTensorflowDistributedDetail from './TensorflowDistributedDetail';
export SdxvTensorflowAutoDistributedDetail from './TensorflowAutoDistributedDetail';
export SdxvContainerDevDetail from './ContainerDevDetail';
export SdxvTensorBoardDetail from './TensorBoardDetail';
export SdxvDataServiceDetail from './DataServiceDetail';
